### ISSUE TITLE
Compilation error in Arduino Sketch

### ISSUE THREAD

**Issue by IceLuck** [wms2537/esp32cam-websockets-stream#1]
Error 1
Line 109: state = 3;
Message error: "state" was not declared in this scope.
Solution: In line 103 add [int state = 0;]

---------------

Error 2
Line 137: break;
Message error: break statement not within loop or swith
Solution: change this line to: ESP.restart();

For me, the compilation ended after the modifications.

**Comment by wms2537** [comment]
Thanks for the fix
